apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
meta
  name: integra
  namespace: platform-pipeline
  annotations:
    kargo.akuity.io/color: yellow
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: platform-apps
    sources:
      stages:
      - test
  
  promotionTemplate:
    spec:
      vars:
      - name: gitRepo
        value: https://username:password@gitea.example.com/org/repo.git  # ← ÄNDERN
      - name: appsPath
        value: apps
      - name: targetBranch
        value: stage/integra
      
      steps:
      - uses: git-clone
        config:
          repoURL: ${{ vars.gitRepo }}
          checkout:
          - fromFreight: true
            path: ./source
          - branch: ${{ vars.targetBranch }}
            create: true
            path: ./out
      
      - uses: git-clear
        config:
          path: ./out
      
      - uses: copy
        config:
          inPath: ./source/${{ vars.appsPath }}
          outPath: ./out/${{ vars.appsPath }}
      
      - uses: git-commit
        config:
          path: ./out
          messageFromSteps:
          - copy
      
      - uses: git-push
        config:
          path: ./out
          targetBranch: ${{ vars.targetBranch }}
