apiVersion: v2
name: kargo
description: Kargo Platform with integrated Pipeline
type: application
version: 1.0.0
appVersion: "1.3.0"

dependencies:
  - name: kargo
    version: 1.3.0
    repository: oci://ghcr.io/akuity/kargo-charts
