{{- range .Values.applications }}
{{- if .enabled }}
---
apiVersion: v1
kind: Namespace
meta
  name: {{ .namespace }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/managed-by: platform-chart
    created-by: platform-helm-chart
{{- end }}
{{- end }}
