apiVersion: v1
kind: ServiceAccount
meta
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: platform
    app.kubernetes.io/managed-by: platform-chart
