{{- if and .Values.pipeline.enabled .Values.pipeline.stages.test.enabled }}
apiVersion: v1
kind: ConfigMap
meta
  name: stage-overrides-test
  namespace: {{ .Values.pipeline.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kargo.stage: test
 {}
{{- end }}
