apiVersion: v1
kind: ConfigMap
meta
  name: stage-overrides-test
  namespace: platform-pipeline
  labels:
    kargo.stage: test
 {}
---
apiVersion: v1
kind: ConfigMap
meta
  name: stage-overrides-integra
  namespace: platform-pipeline
  labels:
    kargo.stage: integra
 {}
---
apiVersion: v1
kind: ConfigMap
meta
  name: stage-overrides-prod
  namespace: platform-pipeline
  labels:
    kargo.stage: prod
 {}
