apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
meta
  name: platform-apps
  namespace: platform-pipeline
spec:
  subscriptions:
  - git:
      repoURL: https://username:password@gitea.example.com/org/repo.git  # ← ÄNDERN
      branch: main
      includePaths:
      - apps/**
